### ISSUE TITLE
Game Manager

### ISSUE THREAD

**Issue by isaac-art** [isaac-art/flown#14]
- [x] Setup basic game manager to handle player and flock data
- [x] Add game state control to change scenes
- [x] Add menus and menu control

**Data**
The data we will be storing is:
- Current 'score' 
- Number of active birds in flock, related to 'score'
- Number of Max birds in flock

**Properties**
From the data spec above, we will be creating and maintaining the following properties (variables):
- score: int
- activeBirds: int
- numOfBirds: int

**Methods**
We will also need some methods (functions) so that we can manage the state information above. 
Within the state manager itself, we will have methods to: 
- Create the state manager instance
- To flush the instance on game exit
- To set the default data
- A method to set the active scene
- A method to return the active scene
- A method to return the players score
- A method to return the active birds info

reference:
[http://www.fizixstudios.com/labs/do/view/id/unity-game-state-manager](http://www.fizixstudios.com/labs/do/view/id/unity-game-state-manager)

[https://unity3d.com/learn/tutorials/projects/2d-roguelike-tutorial/writing-game-manager](https://unity3d.com/learn/tutorials/projects/2d-roguelike-tutorial/writing-game-manager)

**Comment by rebecca-aston** [comment]
Basic Structure

Loader script initializes instance of:
- Game Manager (DONE)
(I like that the tutorial I followed had a sound manager, I guess if we wanted to have ambient sound at menu we could make isaacs sounds stuff into a manager) 

Game Manager manages:
- Level loading (DONE)
- And game state.
(so theoretically if you pause perhaps it stores player position etc etc
for now it just takes you back to menu and play just loads the scene again

Game Manager calls:
- World Manager (This isn't doing anything yet, more of a pseudo-code idea at this stage. we don't have to do it this way necessarily, pulled it from the first link in this ticket).
This would procedurally generate the “level”
Here we would try and control/generate the terrain.
And based on a grid system drop in challenges, i.e. the wind tunnels that speed up the bird etc.
Also an “exit” could be a big hoop or bridge or something that the bird flys through to get to the next level/season.

Game Manager calls:
Have the camera switcher be the parent controller for the actual flying scenes. So when you swipe up to gods eye view the player controller goes into auto pilot etc
- Camera Switcher
    - Swipe Controls
    - Flock generation
        - e.g. have flock distance etc available to push into player controller.
        - Sound controls
    - Player Controller
    - Wide Angle Camera
    - Birds HUD
        - controlling line rendering etc
