### ISSUE TITLE
Add collider trigger script to bird player

### ISSUE THREAD

**Issue by rebecca-aston** [isaac-art/flown#24]

**Comment by isaac-art** [comment]
added playerCollisionReporter.cs attached to Player

The wind zones are reported in the Trigger Events, so would be accessed in:
- 	public Collider triggerCollider;
- 	public Rigidbody triggerRigidbody;
- 	public Bounds triggerBounds;
- 	public bool isTriggered;

Other collisions (ground etc) are in the collision events :

- 	public Collider collisionCollider;
- 	public GameObject collisionGameObject;
- 	public Transform collisionTransform;
- 	public bool isColliding;


Use isColliding or isTriggered to see if the bird has left the collision/trigger state.
